### ISSUE TITLE
elmo-folder-delete-messages-dop-delayed:  What if message-id is nil?

### ISSUE THREAD

**Issue by lawlist** [wanderlust/wanderlust#196]
It has alluded me for years, until today that is, a situation where it is impossible to delete certain emails using Wanderlust.  Today, I traced the issue to an email without a message-id and `elmo-folder-delete-messages-dop-delayed`, which excludes the email to be deleted because `(not (string= (cdr pair) (elmo-message-fetch-field folder (car pair) 'message-id)))`.  I was unsuccessful in my attempts to put in a yes/no prompt to ask me if I wish to delete anyway when the message-id of the desired email cannot be found, however, the code prevents the yes/no prompt from working.

**Comment by ikazuhiro** [comment]
If your problem is really related with `elmo-folder-delete-messages-dop-delayed`, you can delete messages when you are online, is it right?

I don't want to enable that function to delete unsafe messages, that may cause mis-deleting of messages.  Please try [patch](https://gist.github.com/ikazuhiro/fdbf1ae967e5bf8a8754be67a4f029cf) to handle the case that message doesn't have Message-ID header.  In addition the patch shows messages's numbers which are not deleted, so you can delete messages manually.

**Comment by lawlist** [comment]
The patch works, thank you.  And, you are also absolutely correct in that it is possible to delete messages (without a message ID in the header) while online.  Greatly appreciated!

**Comment by ikazuhiro** [comment]
I've committed the patch, so close this issue.
